//Given a sandwich (as an array), return an array of fillings inside the sandwich.
//This involves ignoring the first and last elements.
function getFillings(sandwich) {
    return sandwich.slice(1, -1);
}
import { assertEquals } from '../testHelper.js';
assertEquals(getFillings(["bread", "ham", "cheese", "ham", "bread"]), ["ham", "cheese", "ham"])
assertEquals(getFillings(["bread", "sausage", "tomato", "bread"]), ["sausage", "tomato"])
assertEquals(getFillings(["bread", "lettuce", "bacon", "tomato", "bread"]), ["lettuce", "bacon", "tomato"])
assertEquals(getFillings(["bread", "bacon", "lettuce", "tomato", "bread"]), ["bacon", "lettuce", "tomato"])
assertEquals(getFillings(["bread", "tomato", "tomato", "ham", "sausage", "bread"]), ["tomato", "tomato", "ham", "sausage"])
assertEquals(getFillings(["bread", "lettuce", "bread"]), ["lettuce"])
assertEquals(getFillings(["bread", "cheese", "bread"]), ["cheese"])
assertEquals(getFillings(["bread", "lettuce", "tomato", "ham", "bread"]), ["lettuce", "tomato", "ham"])
assertEquals(getFillings(["bread", "ham", "cheese", "lettuce", "ham", "bread"]), ["ham", "cheese", "lettuce", "ham"])
assertEquals(getFillings(["bread", "lettuce", "lettuce", "bread"]), ["lettuce", "lettuce"])
assertEquals(getFillings(["bread", "sausage", "ham", "bread"]), ["sausage", "ham"])
assertEquals(getFillings(["bread", "bacon", "bread"]), ["bacon"])
assertEquals(getFillings(["bread", "ham", "bread"]), ["ham"])
assertEquals(getFillings(["bread", "ham", "bread"]), ["ham"])
assertEquals(getFillings(["bread", "sausage", "ham", "lettuce", "bread"]), ["sausage", "ham", "lettuce"])
assertEquals(getFillings(["bread", "sausage", "bread"]), ["sausage"])
assertEquals(getFillings(["bread", "lettuce", "bread"]), ["lettuce"])
assertEquals(getFillings(["bread", "tomato", "lettuce", "cheese", "cheese", "bread"]), ["tomato", "lettuce", "cheese", "cheese"])
assertEquals(getFillings(["bread", "tomato", "sausage", "bacon", "tomato", "bread"]), ["tomato", "sausage", "bacon", "tomato"])
assertEquals(getFillings(["bread", "bacon", "ham", "lettuce", "tomato", "lettuce", "bread"]), ["bacon", "ham", "lettuce", "tomato", "lettuce"])
assertEquals(getFillings(["bread", "tomato", "lettuce", "cheese", "lettuce", "bread"]), ["tomato", "lettuce", "cheese", "lettuce"])
assertEquals(getFillings(["bread", "ham", "ham", "bacon", "ham", "cheese", "bread"]), ["ham", "ham", "bacon", "ham", "cheese"])
assertEquals(getFillings(["bread", "tomato", "bacon", "ham", "tomato", "bread"]), ["tomato", "bacon", "ham", "tomato"])
assertEquals(getFillings(["bread", "ham", "cheese", "lettuce", "bread"]), ["ham", "cheese", "lettuce"])
assertEquals(getFillings(["bread", "lettuce", "bread"]), ["lettuce"])
assertEquals(getFillings(["bread", "lettuce", "bacon", "bacon", "bread"]), ["lettuce", "bacon", "bacon"])
assertEquals(getFillings(["bread", "tomato", "cheese", "sausage", "bread"]), ["tomato", "cheese", "sausage"])
assertEquals(getFillings(["bread", "cheese", "ham", "bread"]), ["cheese", "ham"])
assertEquals(getFillings(["bread", "tomato", "bread"]), ["tomato"])
assertEquals(getFillings(["bread", "sausage", "bread"]), ["sausage"])
assertEquals(getFillings(["bread", "cheese", "bread"]), ["cheese"])
assertEquals(getFillings(["bread", "ham", "bacon", "sausage", "lettuce", "sausage", "bread"]), ["ham", "bacon", "sausage", "lettuce", "sausage"])
assertEquals(getFillings(["bread", "cheese", "lettuce", "lettuce", "bacon", "lettuce", "bread"]), ["cheese", "lettuce", "lettuce", "bacon", "lettuce"])
assertEquals(getFillings(["bread", "bacon", "sausage", "ham", "bacon", "bread"]), ["bacon", "sausage", "ham", "bacon"])
assertEquals(getFillings(["bread", "bacon", "tomato", "bread"]), ["bacon", "tomato"])
assertEquals(getFillings(["bread", "tomato", "bread"]), ["tomato"])
assertEquals(getFillings(["bread", "cheese", "cheese", "tomato", "bread"]), ["cheese", "cheese", "tomato"])
assertEquals(getFillings(["bread", "cheese", "tomato", "bread"]), ["cheese", "tomato"])
assertEquals(getFillings(["bread", "lettuce", "bread"]), ["lettuce"])
assertEquals(getFillings(["bread", "lettuce", "sausage", "bread"]), ["lettuce", "sausage"])
assertEquals(getFillings(["bread", "tomato", "tomato", "bread"]), ["tomato", "tomato"])
assertEquals(getFillings(["bread", "tomato", "lettuce", "cheese", "bacon", "bread"]), ["tomato", "lettuce", "cheese", "bacon"])
assertEquals(getFillings(["bread", "tomato", "lettuce", "bread"]), ["tomato", "lettuce"])
assertEquals(getFillings(["bread", "bacon", "bacon", "tomato", "lettuce", "bacon", "bread"]), ["bacon", "bacon", "tomato", "lettuce", "bacon"])
assertEquals(getFillings(["bread", "sausage", "sausage", "lettuce", "bread"]), ["sausage", "sausage", "lettuce"])
assertEquals(getFillings(["bread", "ham", "bacon", "ham", "ham", "bread"]), ["ham", "bacon", "ham", "ham"])
assertEquals(getFillings(["bread", "lettuce", "cheese", "lettuce", "bread"]), ["lettuce", "cheese", "lettuce"])
assertEquals(getFillings(["bread", "ham", "sausage", "cheese", "tomato", "bread"]), ["ham", "sausage", "cheese", "tomato"])
assertEquals(getFillings(["bread", "ham", "cheese", "bacon", "bread"]), ["ham", "cheese", "bacon"])
assertEquals(getFillings(["bread", "cheese", "tomato", "bread"]), ["cheese", "tomato"])
assertEquals(getFillings(["bread", "bacon", "lettuce", "ham", "tomato", "lettuce", "bread"]), ["bacon", "lettuce", "ham", "tomato", "lettuce"])
assertEquals(getFillings(["bread", "ham", "bacon", "bread"]), ["ham", "bacon"])
assertEquals(getFillings(["bread", "ham", "lettuce", "bread"]), ["ham", "lettuce"])