//Given a pH value, return whether that value is "alkaline" (greater than 7), "acidic" (less than 7), or "neutral" (7).
//Return "invalid" if the value given is less than 0 or greater than 14.
function pHName(pH) {
    if (pH < 0 || pH > 14) return "invalid";
    if (pH === 7) return "neutral";
    return pH < 7 ? "acidic" : "alkaline";
}
import { assertEquals } from '../testHelper.js';
assertEquals(pHName(7.0), "neutral")
assertEquals(pHName(7), "neutral")
assertEquals(pHName(13.52), "alkaline")
assertEquals(pHName(-4.33), "invalid")
assertEquals(pHName(8.27), "alkaline")
assertEquals(pHName(9.72), "alkaline")
assertEquals(pHName(-4.58), "invalid")
assertEquals(pHName(14.85), "invalid")
assertEquals(pHName(17.76), "invalid")
assertEquals(pHName(3.9), "acidic")
assertEquals(pHName(14.21), "invalid")
assertEquals(pHName(-2.35), "invalid")
assertEquals(pHName(2.66), "acidic")
assertEquals(pHName(16.45), "invalid")
assertEquals(pHName(3.46), "acidic")
assertEquals(pHName(7.26), "alkaline")
assertEquals(pHName(12.46), "alkaline")
assertEquals(pHName(17.51), "invalid")
assertEquals(pHName(19.7), "invalid")
assertEquals(pHName(10.46), "alkaline")
assertEquals(pHName(-4.83), "invalid")
assertEquals(pHName(3.13), "acidic")
assertEquals(pHName(11.38), "alkaline")
assertEquals(pHName(5.23), "acidic")
assertEquals(pHName(18.85), "invalid")
assertEquals(pHName(15.82), "invalid")
assertEquals(pHName(9.17), "alkaline")
assertEquals(pHName(2.73), "acidic")
assertEquals(pHName(10.99), "alkaline")
assertEquals(pHName(-3.86), "invalid")
assertEquals(pHName(17.59), "invalid")
assertEquals(pHName(5.5), "acidic")
assertEquals(pHName(-3.35), "invalid")
assertEquals(pHName(16.02), "invalid")
assertEquals(pHName(8.78), "alkaline")
assertEquals(pHName(18.94), "invalid")
assertEquals(pHName(-4.69), "invalid")
assertEquals(pHName(0.86), "acidic")
assertEquals(pHName(-3.45), "invalid")
assertEquals(pHName(19.05), "invalid")
assertEquals(pHName(5.41), "acidic")
assertEquals(pHName(0.44), "acidic")
assertEquals(pHName(8.82), "alkaline")
assertEquals(pHName(-1.24), "invalid")
assertEquals(pHName(1.72), "acidic")
assertEquals(pHName(10.01), "alkaline")
assertEquals(pHName(3.49), "acidic")
assertEquals(pHName(13.62), "alkaline")
assertEquals(pHName(3.43), "acidic")
assertEquals(pHName(4.35), "acidic")
assertEquals(pHName(17.07), "invalid")
assertEquals(pHName(14.64), "invalid")
